In [11]:
import math
import numpy as np

In [12]:

def basic_sigmoid(x):


    s=1/(1+math.exp(x))
    return s

In [13]:
basic_sigmoid(-1)

0.7310585786300049

In [14]:
x=np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [15]:
def basic_sigmoid(x):


    s=1/(1+np.exp(x))
    return s

In [16]:
basic_sigmoid(-1)

0.7310585786300049

In [10]:
x=np.array([1,2,3])
basic_sigmoid(x)

array([0.26894142, 0.11920292, 0.04742587])

In [22]:
def basic_sigmoid_derivative(x):
    s = 1/(1+np.exp(-x))
    ds = s * (1-s)
    return ds

In [23]:
x= np.array([1,2,3])
print("basic_sigmoid_derivative",str(basic_sigmoid_derivative(x)))

basic_sigmoid_derivative [0.19661193 0.10499359 0.04517666]


In [30]:
image = np.array([[[0.67826139, 0.25386381],
                   [0.90714082, 0.52835647],
                   [0.4215251, 0.45017551]],
               
                  [[0.92814219, 0.00077647],
                   [0.85384783, 0.52353845],
                   [0.19981347, 0.27417311]],

                  [[0.60659855, 0.00533165],
                   [0.10820313, 0.49978937],
                   [0.34144279, 0.94630077]]])

In [35]:
def image2vector(image):
    vec = image.reshape((image.shape[0]*image.shape[1]*image.shape[2], 1))
    return vec

In [37]:
image2vector(image)

array([[6.7826139e-01],
       [2.5386381e-01],
       [9.0714082e-01],
       [5.2835647e-01],
       [4.2152510e-01],
       [4.5017551e-01],
       [9.2814219e-01],
       [7.7647000e-04],
       [8.5384783e-01],
       [5.2353845e-01],
       [1.9981347e-01],
       [2.7417311e-01],
       [6.0659855e-01],
       [5.3316500e-03],
       [1.0820313e-01],
       [4.9978937e-01],
       [3.4144279e-01],
       [9.4630077e-01]])

In [40]:
def normalization(x):
    x_norm = np.linalg.norm(x, axis=1, keepdims= True)
    x=x/x_norm
    return x

In [41]:
x = np.array([[0,100,4],[2,6,4]])
print("normalized rows:" , normalization(x))

normalized rows: [[0.         0.99920096 0.03996804]
 [0.26726124 0.80178373 0.53452248]]


In [46]:
def softmax(x):
    x_exp = np.exp(x)
    
    x_sum = np.sum(x_exp, axis=1, keepdims = True)
    
    s = x_exp / x_sum
    
    return s

In [47]:
x = np.array([[3,4,5,8],
            [1,2,6,7]])
softmax(x)

array([[0.00626879, 0.01704033, 0.04632042, 0.93037047],
       [0.00179998, 0.00489287, 0.26714144, 0.72616571]])

In [48]:
import time

x1 = [9,2,5,0,0,7,5,0,0,0,9,2,5,0,0]
x2 = [9,2,2,9,0,9,2,5,0,0,9,2,5,0,0]

tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print(str(dot)+"\n"+ str(1000*(toc-tic))+"ms")

tic = time.process_time()
outer = np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
    for j in range(len(x1)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print(str(outer)+"\n"+ str(1000*(toc-tic))+"ms")

278
0.0ms
[[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
0.0ms
